### ISSUE TITLE
Lon/Latitude/CRS issues

### ISSUE THREAD

**Issue by jimr1603** [Robinlovelace/rvalhalla#2]
Latitude & Longitude is being scaled up 10 times in the googlepolylines decoding step. 

At this point in the pipeline it makes sense to slap WGS84 CRS on the sf object, so I'm flagging "sf object has no CRS" as the same issue.

**Comment by Robinlovelace** [comment]
Thanks @jimr1603 and sorry for being a bit slow to see this. Agreed, why does it happen? will look at your PR in any case..
